### ISSUE TITLE
Download songs -> Sync songs

### ISSUE THREAD

**Issue by p2kmgcl** [clementine-player/Android-Remote#113]
It would be wonderfull if downloading songs clementine updated rating and/or song's playcounts stored on file's metadata like:
1. Download song "x" to phone with a playcount of 3 and no rating.
2. Play the song on phone twice and rate it with an 8 (playcount 5).
3. Play the song on computer once (playcount in computer 4).
4. Re-Download the song: playcount of 6 and rating of 8 in both devices.

I think this would need an extra tag like "last sync date" or something like that. It could be quite complicated but is just a suggestion :3

**Comment by qkslvrwolf** [comment]
+1 for this!  Although, in my dreams, the "remote" is both remote and offline player, and would have the capability to sync playcounts back to the central server.

**Comment by amuttsch** [comment]
Sync the playcount won't be possible. Clementine Remote doesn't know how many times you played the track on the device. Playcounts aren't stored in the file itself, so there is no way updating this information. What player do you use to update the rating and see the playcount on Android?

Clementine and other players can store the rating in the file itself. But since the varaity of media players on android, I don't know if they support this format or if they store the rating in their database. I don't see much benefit in syncing the rating in comparison to the effort to implement this.

An offline player won't be integrated as there are a lot great players for Android with a large feature set on Google Play.

**Comment by qkslvrwolf** [comment]
But what I love about clementine is its ability to collect data about what I like to listen to, to sort of tell me what I like and what I don't like.  If I'm loading music on my phone based on it being music that I always like to listen to, but then skipping it frequently when I'm playing in the car, that's information that I want to know.  That's why I'd love it if I could maintain all my music listening from within the same clementine ecosystem.

**Comment by p2kmgcl** [comment]
When I proposed that I was thinking about the `FMPS_Playcount` tag that clementine optionaly uses, but it's true than on android no player uses playcount parameters :(

I think the only posible solution is what @qkslvrwolf says: converting clementine remote into a complete player, but that may be a too hard work for solving a "playcount sync problem".
